# fly.toml app configuration file generated for svwefsbr-game-website on 2023-07-11T15:04:06-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "svwefsbr-game-website"
primary_region = "sjc"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
